# Generated by Django 3.0.4 on 2020-05-16 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(choices=[('Dolnoskaskie', 'Dolnoskaskie'), ('Kujawsko-Pomorskie', 'Kujawsko-Pomorskie'), ('Lubelskie', 'Lubelskie'), ('Lubuskie', 'Lubuskie'), ('Lodzkie', 'Lodzkie'), ('Malopolskie', 'Malopolskie'), ('Mazowieckie', 'Mazowieckie'), ('Opolskie', 'Opolskie'), ('Podkarpackie', 'Podkarpackie'), ('Podlaskie', 'Podlaskie'), ('Pomorskie', 'Pomorskie'), ('Slaskie', 'Slaskie'), ('Swietokrzyskie', 'Swietokrzyskie'), ('Warminsko-Mazurskie', 'Warminsko-Mazurskie'), ('Wielkopolskie', 'Wielkopolskie'), ('Zachodniopomorskie', 'Zachodniopomorskie')], max_length=30)),
                ('category', models.CharField(choices=[('Motoryzacja', 'Motoryzacja'), ('Dom', 'Dom'), ('Ogrod', 'Ogrod'), ('Elektronika', 'Elektronika'), ('Moda', 'Moda'), ('Rolnictwo', 'Rolnictwo'), ('Zwierzeta', 'Zwierzeta'), ('Dziecko', 'Dziecko'), ('Sport', 'Sport'), ('Hobby', 'Hobby'), ('Muzyka', 'Muzyka'), ('Edukacja', 'Edukacja'), ('Materialy Budowlane', 'Materialy Budowlane'), ('Zdrowie', 'Zdrowie'), ('Uroda', 'Uroda')], max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
