# Generated by Django 3.1.4 on 2020-12-26 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1, null=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('nailing', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchGroupStageReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_team_one', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True)),
                ('goals_team_two', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True)),
                ('score_team_one', models.CharField(choices=[('WIN', 'WIN'), ('DRAW', 'DRAW'), ('DEFEAT', 'DEFEAT')], max_length=6, null=True)),
                ('score_team_two', models.CharField(choices=[('WIN', 'WIN'), ('DRAW', 'DRAW'), ('DEFEAT', 'DEFEAT')], max_length=6, null=True)),
                ('team_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_one_group', to='betting_manager.team')),
                ('team_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_two_group', to='betting_manager.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchGroupStageBetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_team_one', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('goals_team_two', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('score_team_one', models.CharField(choices=[('WIN', 'WIN'), ('DRAW', 'DRAW'), ('DEFEAT', 'DEFEAT')], max_length=6, null=True)),
                ('score_team_two', models.CharField(choices=[('WIN', 'WIN'), ('DRAW', 'DRAW'), ('DEFEAT', 'DEFEAT')], max_length=6, null=True)),
                ('points', models.IntegerField(default=0)),
                ('checked', models.BooleanField(default=False)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting_manager.matchgroupstagereal')),
                ('person_betting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting_manager.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchFinalStageReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_team_one', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True)),
                ('goals_team_two', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True)),
                ('penalties_team_one', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True)),
                ('penalties_team_two', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True)),
                ('score_team_one', models.CharField(choices=[('WIN', 'WIN'), ('DEFEAT', 'DEFEAT')], max_length=6, null=True)),
                ('score_team_two', models.CharField(choices=[('WIN', 'WIN'), ('DEFEAT', 'DEFEAT')], max_length=6, null=True)),
                ('team_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_one_final', to='betting_manager.team')),
                ('team_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_two_final', to='betting_manager.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchFinalStageBetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_team_one', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('goals_team_two', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('score_team_one', models.CharField(choices=[('WIN', 'WIN'), ('DEFEAT', 'DEFEAT')], max_length=6, null=True)),
                ('score_team_two', models.CharField(choices=[('WIN', 'WIN'), ('DEFEAT', 'DEFEAT')], max_length=6, null=True)),
                ('penalties_team_one', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True)),
                ('penalties_team_two', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True)),
                ('points', models.IntegerField(default=0)),
                ('checked', models.BooleanField(default=False)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting_manager.matchfinalstagereal')),
                ('person_betting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting_manager.player')),
            ],
        ),
    ]
