# Generated by Django 3.1.4 on 2020-12-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_manager', '0002_auto_20201227_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfinalstagereal',
            name='goals_team_one',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='matchfinalstagereal',
            name='goals_team_two',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='matchgroupstagereal',
            name='goals_team_one',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='matchgroupstagereal',
            name='goals_team_two',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=1, null=True),
        ),
    ]
