# Generated by Django 3.1.4 on 2020-12-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_manager', '0004_auto_20201227_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfinalstagebetting',
            name='checked',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matchgroupstagebetting',
            name='checked',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
    ]
