# Generated by Django 3.1.4 on 2020-12-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_manager', '0005_auto_20201227_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nailing',
            field=models.IntegerField(default=0),
        ),
    ]
