# Generated by Django 3.1.4 on 2020-12-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting_manager', '0006_team_nailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='nailing',
        ),
    ]
