# Generated by Django 3.0.4 on 2020-09-13 07:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('naming', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('service', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(choices=[('AUDI', 'AUDI'), ('BMW', 'BMW'), ('CHEVROLET', 'CHEVROLET'), ('CITROEN', 'CITROEN'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('HONDA', 'HONDA'), ('HYUNDAI', 'HYUNDAI'), ('KIA', 'KIA'), ('MAZDA', 'MAZDA'), ('MERCEDES', 'MERCEDES'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSA', 'NISSAN'), ('OPEL', 'OPEL'), ('PEUGEOT', 'PEUGEOT'), ('RENAULT', 'RENAULT'), ('SEAT', 'SEAT'), ('SKODA', 'SKODA'), ('TOYOTA', 'TOYOTA'), ('VOLKSWAGEN', 'VOLKSWAGEN')], max_length=15, null=True)),
                ('fix_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_provided', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.Product')),
                ('service_provided', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.Service')),
            ],
        ),
    ]
