# Generated by Django 3.1.4 on 2020-12-09 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('zone', models.CharField(choices=[('Dolnoskaskie', 'Dolnoskaskie'), ('Kujawsko-Pomorskie', 'Kujawsko-Pomorskie'), ('Lubelskie', 'Lubelskie'), ('Lubuskie', 'Lubuskie'), ('Lodzkie', 'Lodzkie'), ('Malopolskie', 'Malopolskie'), ('Mazowieckie', 'Mazowieckie'), ('Opolskie', 'Opolskie'), ('Podkarpackie', 'Podkarpackie'), ('Podlaskie', 'Podlaskie'), ('Pomorskie', 'Pomorskie'), ('Slaskie', 'Slaskie'), ('Swietokrzyskie', 'Swietokrzyskie'), ('Warminsko-Mazurskie', 'Warminsko-Mazurskie'), ('Wielkopolskie', 'Wielkopolskie'), ('Zachodniopomorskie', 'Zachodniopomorskie')], max_length=20, null=True)),
                ('category', models.CharField(choices=[('Motoryzacja', 'Motoryzacja'), ('Dom', 'Dom'), ('Ogrod', 'Ogrod'), ('Elektronika', 'Elektronika'), ('Moda', 'Moda'), ('Rolnictwo', 'Rolnictwo'), ('Zwierzeta', 'Zwierzeta'), ('Dziecko', 'Dziecko'), ('Sport', 'Sport'), ('Hobby', 'Hobby'), ('Muzyka', 'Muzyka'), ('Edukacja', 'Edukacja'), ('Materialy Budowlane', 'Materialy Budowlane'), ('Zdrowie', 'Zdrowie'), ('Uroda', 'Uroda')], max_length=25, null=True)),
                ('state', models.CharField(choices=[('Nowe', 'Nowe'), ('Używane', 'Używane')], max_length=10, null=True)),
                ('time_registered', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Aktywne', 'Aktywne'), ('Zamknięte', 'Zamknięte')], max_length=13, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sheriffy.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_photos')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sheriffy.item')),
            ],
        ),
    ]
