# Generated by Django 3.1.4 on 2020-12-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheriffy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='city',
        ),
    ]
