# Generated by Django 3.1.4 on 2020-12-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheriffy', '0002_remove_item_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
