# Generated by Django 3.0.4 on 2020-08-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotrequesting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='spot_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=6),
        ),
    ]
