# Generated by Django 3.0.4 on 2020-08-06 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotrequesting', '0002_auto_20200802_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='dest_country',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Country code is two letters', regex='[A-Z]{2}')]),
        ),
        migrations.AlterField(
            model_name='spot',
            name='dest_port',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Port code is three letters', regex='[A-Z]{3}')]),
        ),
        migrations.AlterField(
            model_name='spot',
            name='origin_country',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Country code is two letters', regex='[A-Z]{2}')]),
        ),
        migrations.AlterField(
            model_name='spot',
            name='origin_port',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Port code is three letters', regex='[A-Z]{3}')]),
        ),
        migrations.AlterField(
            model_name='spot',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotrequesting.Stakeholder'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='ship_week',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
