# Generated by Django 3.0.4 on 2020-08-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotrequesting', '0003_auto_20200806_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='carrier_id',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='spot_id',
            new_name='spot',
        ),
    ]
