# Generated by Django 3.0.4 on 2020-08-16 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotrequesting', '0004_auto_20200816_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotrequesting.Stakeholder'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotrequesting.Spot'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='carrier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotrequesting.Stakeholder'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='spot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotrequesting.Spot'),
        ),
    ]
