# Generated by Django 3.0.4 on 2020-08-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotrequesting', '0009_auto_20200829_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(default='pending', max_length=8),
        ),
    ]
