# Generated by Django 3.0.4 on 2020-09-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotrequesting', '0012_auto_20200830_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='company_name',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='group',
            field=models.CharField(choices=[('F&D', 'F&D'), ('key_user', 'key_user'), ('carrier', 'carrier')], default='key_user', max_length=15),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=8),
        ),
    ]
