# Generated by Django 3.1.4 on 2021-03-31 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_period_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='back_up',
        ),
        migrations.RemoveField(
            model_name='status',
            name='owner',
        ),
        migrations.AddField(
            model_name='report',
            name='back_up',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup', to='tracker.person'),
        ),
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='tracker.person'),
        ),
    ]
