# Generated by Django 3.1.4 on 2021-03-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210331_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='deadline',
            field=models.CharField(choices=[('BD 1', 'BD 1'), ('BD 2', 'BD 2'), ('BD 3', 'BD 3'), ('BD 4', 'BD 4'), ('BD 5', 'BD 5'), ('BD 6', 'BD 6'), ('BD 7', 'BD 7'), ('BD 8', 'BD 8'), ('BD 9', 'BD 9'), ('BD 10', 'BD 10'), ('BD 11', 'BD 11'), ('BD 12', 'BD 12'), ('BD 13', 'BD 13'), ('BD 14', 'BD 14'), ('BD 15', 'BD 15')], max_length=5, null=True),
        ),
    ]
