# Generated by Django 3.1.4 on 2021-04-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210331_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='business_area',
        ),
        migrations.AddField(
            model_name='report',
            name='business_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.business'),
        ),
    ]
