# Generated by Django 3.1.4 on 2021-01-05 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='energy_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('paid', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('consumption', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('period', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, null=True)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bill_photos')),
            ],
        ),
        migrations.CreateModel(
            name='gas_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('paid', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('consumption', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('period', models.CharField(choices=[('January - February', 'January - February'), ('March - April', 'March - April'), ('May - June', 'May - June'), ('July - August', 'July - August'), ('September - October', 'September - October'), ('November - December', 'November - December')], max_length=19, null=True)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bill_photos')),
            ],
        ),
        migrations.CreateModel(
            name='home_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_warm', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('consumption_warm', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('price_cold', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('consumption_cold', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('paid', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('period', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, null=True)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bill_photos')),
            ],
        ),
        migrations.CreateModel(
            name='internet_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('paid', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('period', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, null=True)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bill_photos')),
            ],
        ),
        migrations.CreateModel(
            name='tv_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=5)])),
                ('paid', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('period', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, null=True)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bill_photos')),
            ],
        ),
    ]
