# Generated by Django 3.1.4 on 2021-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy_bill',
            name='year',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
        migrations.AddField(
            model_name='gas_bill',
            name='year',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
        migrations.AddField(
            model_name='home_bill',
            name='year',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
        migrations.AddField(
            model_name='internet_bill',
            name='year',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
        migrations.AddField(
            model_name='tv_bill',
            name='year',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], null=True),
        ),
    ]
