# Generated by Django 3.0.4 on 2020-07-06 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('Password expired', 'Password expired'), ('Account blocked', 'Account blocked'), ("Don't remember the password", "Don't remember the password"), ('Other', 'Other')], max_length=30)),
                ('content', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Solved', 'Solved')], default='New', max_length=10)),
                ('kuser', models.CharField(choices=[('Erik Alexander', 'Erik Alexander'), ('Nadja Quesada', 'Nadja Quesada'), ('Mellen Lopez', 'Mellen Lopez'), ('Krystian Krawczyk', 'Krystian Krawczyk'), ('Maciej Janowski', 'Maciej Janowski')], max_length=20)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
