# Generated by Django 3.1.4 on 2021-01-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210109_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentair',
            name='page',
        ),
        migrations.RemoveField(
            model_name='shipmentfcl',
            name='page',
        ),
        migrations.RemoveField(
            model_name='shipmentlcl',
            name='page',
        ),
        migrations.RemoveField(
            model_name='shipmentroadeu',
            name='page',
        ),
        migrations.RemoveField(
            model_name='shipmentroadus',
            name='page',
        ),
    ]
