# Generated by Django 3.1.4 on 2021-01-15 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20210109_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentOverviewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_all', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('coverage_src', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('coverage_matc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('coverage_dap', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('reporting_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentsOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_all', models.IntegerField(null=True)),
                ('missing_src', models.IntegerField(null=True)),
                ('missing_matc', models.IntegerField(null=True)),
                ('missing_dap', models.IntegerField(null=True)),
                ('date_registered', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
