# Generated by Django 3.1.4 on 2021-01-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_shipmentoverviewhistory_shipmentsoverview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentoverviewhistory',
            name='coverage_dap',
        ),
        migrations.RemoveField(
            model_name='shipmentoverviewhistory',
            name='coverage_matc',
        ),
        migrations.RemoveField(
            model_name='shipmentoverviewhistory',
            name='coverage_src',
        ),
    ]
