# Generated by Django 3.0.4 on 2020-09-06 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=10, null=True)),
                ('laneid', models.CharField(max_length=11, null=True)),
                ('origin_country', models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Country code is two letters', regex='[A-Z]{2}')])),
                ('origin_port', models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Port code is three letters', regex='[A-Z]{3}')])),
                ('dest_country', models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Country code is two letters', regex='[A-Z]{2}')])),
                ('dest_port', models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Port code is three letters', regex='[A-Z]{3}')])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency is three letters', regex='[A-Z]{3}')])),
                ('pickup', models.FloatField(default=0)),
                ('origin_cust', models.FloatField(default=0)),
                ('origin_hand', models.FloatField(default=0)),
                ('airfreight', models.FloatField(default=0)),
                ('dest_cust', models.FloatField(default=0)),
                ('dest_hand', models.FloatField(default=0)),
                ('delivery', models.FloatField(default=0)),
                ('screening', models.FloatField(default=0)),
                ('screening_metric', models.CharField(choices=[('KG', 'KG'), ('SHIPMENT', 'SHIPMENT')], default='KG', max_length=8)),
                ('dgfee', models.FloatField(default=0)),
                ('dg_metric', models.CharField(choices=[('KG', 'KG'), ('SHIPMENT', 'SHIPMENT')], default='KG', max_length=8)),
            ],
        ),
    ]
