# Generated by Django 3.0.4 on 2020-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlane',
            name='service_lvl',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
